#!/usr/bin/env python3
import json
from concurrent import futures

import grpc

import appfs_adapter_v1_pb2 as pb2
import appfs_adapter_v1_pb2_grpc as pb2_grpc


class BridgeService(pb2_grpc.AppfsAdapterBridgeServicer):
    def SubmitAction(self, request: pb2.SubmitActionRequest, context: grpc.ServicerContext):
        path = request.path
        execution_mode = request.execution_mode

        if execution_mode == pb2.EXECUTION_MODE_INLINE:
            if path.endswith("/send_message.act"):
                return pb2.SubmitActionResponse(
                    completed=pb2.CompletedOutcome(content_json=json.dumps("send success"))
                )
            return pb2.SubmitActionResponse(
                completed=pb2.CompletedOutcome(content_json=json.dumps("action completed"))
            )

        terminal = {"ok": True}
        if path.endswith("/download.act"):
            try:
                payload = json.loads(request.payload)
                terminal = {"saved_to": payload.get("target", "unknown")}
            except Exception:
                terminal = {"saved_to": "unknown"}

        return pb2.SubmitActionResponse(
            streaming=pb2.StreamingOutcome(
                accepted_content_json=json.dumps("accepted"),
                progress_content_json=json.dumps({"percent": 50}),
                terminal_content_json=json.dumps(terminal),
                has_accepted_content=True,
                has_progress_content=True,
            )
        )

    def SubmitControlAction(
        self, request: pb2.SubmitControlActionRequest, context: grpc.ServicerContext
    ):
        which = request.WhichOneof("action")

        if which == "paging_fetch_next":
            action = request.paging_fetch_next
            content = {
                "items": [{"id": f"m-{action.page_no}", "text": "generated by grpc bridge"}],
                "page": {
                    "handle_id": action.handle_id,
                    "page_no": action.page_no,
                    "has_more": action.has_more,
                    "mode": "snapshot",
                },
            }
            return pb2.SubmitControlActionResponse(
                completed=pb2.ControlCompletedOutcome(content_json=json.dumps(content))
            )

        if which == "paging_close":
            action = request.paging_close
            content = {"closed": True, "handle_id": action.handle_id}
            return pb2.SubmitControlActionResponse(
                completed=pb2.ControlCompletedOutcome(content_json=json.dumps(content))
            )

        return pb2.SubmitControlActionResponse(
            error=pb2.BridgeError(
                code="NOT_SUPPORTED",
                message=f"unsupported control action: {which}",
                retryable=False,
            )
        )


def main() -> None:
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=8))
    pb2_grpc.add_AppfsAdapterBridgeServicer_to_server(BridgeService(), server)
    server.add_insecure_port("127.0.0.1:50051")
    server.start()
    print("AppFS gRPC bridge listening on 127.0.0.1:50051")
    server.wait_for_termination()


if __name__ == "__main__":
    main()
