#!/usr/bin/env python3
import json
from http.server import BaseHTTPRequestHandler, HTTPServer


def _json_response(handler: BaseHTTPRequestHandler, status: int, body: dict) -> None:
    payload = json.dumps(body).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json")
    handler.send_header("Content-Length", str(len(payload)))
    handler.end_headers()
    handler.wfile.write(payload)


class BridgeHandler(BaseHTTPRequestHandler):
    def do_POST(self) -> None:
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length)
        try:
            data = json.loads(raw.decode("utf-8"))
        except json.JSONDecodeError:
            _json_response(
                self,
                400,
                {
                    "kind": "rejected",
                    "code": "INVALID_ARGUMENT",
                    "message": "invalid json body",
                    "retryable": False,
                },
            )
            return

        if self.path == "/v1/submit-action":
            self.handle_submit_action(data)
            return
        if self.path == "/v1/submit-control-action":
            self.handle_submit_control(data)
            return

        _json_response(
            self,
            404,
            {"kind": "internal", "message": f"unknown path: {self.path}"},
        )

    def handle_submit_action(self, data: dict) -> None:
        path = str(data.get("path", ""))
        execution_mode = str(data.get("execution_mode", "inline"))
        payload = str(data.get("payload", ""))

        if execution_mode == "inline":
            if path.endswith("/send_message.act"):
                _json_response(self, 200, {"kind": "completed", "content": "send success"})
                return
            _json_response(self, 200, {"kind": "completed", "content": "action completed"})
            return

        terminal_content = {"ok": True}
        if path.endswith("/download.act"):
            try:
                parsed = json.loads(payload)
                target = parsed.get("target", "unknown")
            except Exception:
                target = "unknown"
            terminal_content = {"saved_to": target}

        _json_response(
            self,
            200,
            {
                "kind": "streaming",
                "plan": {
                    "accepted_content": "accepted",
                    "progress_content": {"percent": 50},
                    "terminal_content": terminal_content,
                },
            },
        )

    def handle_submit_control(self, data: dict) -> None:
        action = data.get("action", {}) or {}
        kind = str(action.get("kind", ""))

        if kind == "paging_fetch_next":
            handle_id = str(action.get("handle_id", ""))
            page_no = int(action.get("page_no", 1))
            has_more = bool(action.get("has_more", False))
            _json_response(
                self,
                200,
                {
                    "kind": "completed",
                    "content": {
                        "items": [{"id": f"m-{page_no}", "text": "generated by python bridge"}],
                        "page": {
                            "handle_id": handle_id,
                            "page_no": page_no,
                            "has_more": has_more,
                            "mode": "snapshot",
                        },
                    },
                },
            )
            return

        if kind == "paging_close":
            handle_id = str(action.get("handle_id", ""))
            _json_response(
                self,
                200,
                {
                    "kind": "completed",
                    "content": {"closed": True, "handle_id": handle_id},
                },
            )
            return

        _json_response(
            self,
            400,
            {
                "kind": "rejected",
                "code": "NOT_SUPPORTED",
                "message": f"unsupported control action: {kind}",
                "retryable": False,
            },
        )

    def log_message(self, format: str, *args) -> None:
        # Keep output concise for contract-test runs.
        return


def main() -> None:
    server = HTTPServer(("127.0.0.1", 8080), BridgeHandler)
    print("AppFS HTTP bridge listening on http://127.0.0.1:8080")
    server.serve_forever()


if __name__ == "__main__":
    main()
