use crate::{
    AdapterControlActionV1, AdapterControlOutcomeV1, AdapterErrorV1, AdapterExecutionModeV1,
    AdapterInputModeV1, AdapterStreamingPlanV1, AdapterSubmitOutcomeV1, AppAdapterV1,
    RequestContextV1,
};
use serde_json::{json, Value as JsonValue};

/// Reference demo adapter implementation for AppFS v0.1.
///
/// This adapter is intentionally simple and deterministic so runtime and
/// conformance flows can be validated without app-specific backends.
pub struct DemoAppAdapterV1 {
    app_id: String,
}

impl DemoAppAdapterV1 {
    pub fn new(app_id: String) -> Self {
        Self { app_id }
    }
}

impl AppAdapterV1 for DemoAppAdapterV1 {
    fn app_id(&self) -> &str {
        &self.app_id
    }

    fn submit_action(
        &mut self,
        path: &str,
        payload: &str,
        _input_mode: AdapterInputModeV1,
        execution_mode: AdapterExecutionModeV1,
        _ctx: &RequestContextV1,
    ) -> std::result::Result<AdapterSubmitOutcomeV1, AdapterErrorV1> {
        match execution_mode {
            AdapterExecutionModeV1::Inline => {
                let content = if path.ends_with("/send_message.act") {
                    json!("send success")
                } else {
                    json!("action completed")
                };
                Ok(AdapterSubmitOutcomeV1::Completed { content })
            }
            AdapterExecutionModeV1::Streaming => {
                let terminal = if path.ends_with("/download.act") {
                    if let Ok(json) = serde_json::from_str::<JsonValue>(payload) {
                        if let Some(target) = json.get("target").and_then(|v| v.as_str()) {
                            json!({ "saved_to": target })
                        } else {
                            json!({ "saved_to": "unknown" })
                        }
                    } else {
                        json!({ "saved_to": "unknown" })
                    }
                } else {
                    json!("action completed")
                };

                Ok(AdapterSubmitOutcomeV1::Streaming {
                    plan: AdapterStreamingPlanV1 {
                        accepted_content: Some(json!("accepted")),
                        progress_content: Some(json!({ "percent": 50 })),
                        terminal_content: terminal,
                    },
                })
            }
        }
    }

    fn submit_control_action(
        &mut self,
        _path: &str,
        action: AdapterControlActionV1,
        _ctx: &RequestContextV1,
    ) -> std::result::Result<AdapterControlOutcomeV1, AdapterErrorV1> {
        match action {
            AdapterControlActionV1::PagingFetchNext {
                handle_id,
                page_no,
                has_more,
            } => Ok(AdapterControlOutcomeV1::Completed {
                content: json!({
                    "items": [
                        {
                            "id": format!("m-{}", page_no),
                            "text": "generated by appfs adapter"
                        }
                    ],
                    "page": {
                        "handle_id": handle_id,
                        "page_no": page_no,
                        "has_more": has_more,
                        "mode": "snapshot"
                    }
                }),
            }),
            AdapterControlActionV1::PagingClose { handle_id } => {
                Ok(AdapterControlOutcomeV1::Completed {
                    content: json!({
                        "closed": true,
                        "handle_id": handle_id
                    }),
                })
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::DemoAppAdapterV1;
    use crate::{
        AdapterControlActionV1, AdapterControlOutcomeV1, AdapterExecutionModeV1,
        AdapterInputModeV1, AdapterSubmitOutcomeV1, AppAdapterV1, RequestContextV1,
    };

    fn ctx() -> RequestContextV1 {
        RequestContextV1 {
            app_id: "aiim".to_string(),
            session_id: "sess-test".to_string(),
            request_id: "req-1".to_string(),
            client_token: Some("tok-1".to_string()),
        }
    }

    #[test]
    fn demo_adapter_inline_action() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let result = adapter
            .submit_action(
                "/contacts/zhangsan/send_message.act",
                "hello\n",
                AdapterInputModeV1::Text,
                AdapterExecutionModeV1::Inline,
                &ctx(),
            )
            .expect("inline action should succeed");
        match result {
            AdapterSubmitOutcomeV1::Completed { content } => {
                assert_eq!(content, "send success");
            }
            _ => panic!("expected inline completed"),
        }
    }

    #[test]
    fn demo_adapter_streaming_action() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let result = adapter
            .submit_action(
                "/files/file-001/download.act",
                r#"{"target":"/tmp/a.bin"}"#,
                AdapterInputModeV1::Json,
                AdapterExecutionModeV1::Streaming,
                &ctx(),
            )
            .expect("streaming action should succeed");
        match result {
            AdapterSubmitOutcomeV1::Streaming { plan } => {
                assert!(plan.accepted_content.is_some());
                assert!(plan.progress_content.is_some());
                assert_eq!(plan.terminal_content["saved_to"], "/tmp/a.bin");
            }
            _ => panic!("expected streaming outcome"),
        }
    }

    #[test]
    fn demo_adapter_control_action() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let result = adapter
            .submit_control_action(
                "/_paging/close.act",
                AdapterControlActionV1::PagingClose {
                    handle_id: "ph_abc".to_string(),
                },
                &ctx(),
            )
            .expect("control action should succeed");
        match result {
            AdapterControlOutcomeV1::Completed { content } => {
                assert_eq!(content["closed"], true);
                assert_eq!(content["handle_id"], "ph_abc");
            }
        }
    }
}
